name: quokka
description: Play games without internet

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: any
  flutter_localized_locales: ^2.0.5
  # UI
  phosphor_flutter: ^2.1.0
  material_leap:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: e844798751461be17a633fc98565a1aa9003a297
      path: packages/material_leap
  flex_color_scheme:
    git:
      url: https://github.com/rydmike/flex_color_scheme
      ref: 6b34ee7d2efcf0d964163e925ba946a7bf454d72
  flutter_svg: ^2.0.10+1
  window_manager: ^0.4.0
  go_router: ^14.2.2
  # Database
  shared_preferences: ^2.3.1
  # Generation
  barcode: ^2.2.7
  # Internal
  flutter_bloc: ^8.1.3
  rxdart: ^0.28.0
  collection: ^1.18.0
  flame_bloc: 1.12.0
  flame: 1.18.0
  flame_tiled: 1.20.2
  # Networking
  http: ^1.2.1
  web_socket_channel: ^3.0.0
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      ref: b440166c38b927b6520f2835ceffb860b88faa30
      path: packages/networker/networker
  networker_socket:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      ref: 8dc38c743c8dc3450e5c5a2f64536ef590e8d376
      path: packages/networker/networker_socket
  # System Information
  dynamic_color: ^1.7.0
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.4
  url_launcher: ^6.2.6
  file_selector: ^1.0.3
  lw_file_system:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: 57a458aa5644b9b3069d1266a411c868686cd9f4
      path: packages/lw_file_system
  lw_sysapi:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: 21808e89bb6239f0b39367d0c00b0b14f5273992
      path: packages/lw_sysapi
  # Serialization
  json_annotation: ^4.9.0
  dart_mappable: ^4.2.2
  archive: ^3.4.10
dependency_overrides:
  flutter_secure_storage_web:
    git:
      url: https://github.com/CodeDoctorDE/flutter_secure_storage.git
      ref: 1d7b32bde7910bc2ffd1db5245ee0b2478ff4b7d
      path: flutter_secure_storage_web
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  dart_mappable_builder: ^4.2.3
  integration_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/pack.qka
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: assets/fonts/Schyler-Regular.ttf
  #       - asset: assets/fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fontsassets//#from-packages
