name: qeck
description: Play games without internet

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter  
  intl: ^0.18.1
  flutter_localized_locales: ^2.0.5
  # Engine
  flame: ^1.12.0
  # UI
  phosphor_flutter:
    git:
      url: https://github.com/CodeDoctorDE/phosphor-flutter
      ref: f370dd2c25d3ea51ffb8f1c7c183bc9f33889c82
  material_leap:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: 7a0a8dc7eaca62e83d85259dab12e11b5f14ac8e
      path: packages/material_leap
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: 51e8e6e0f3531c35f9d4f34f04ac1235e74fea9b
      path: packages/networker/networker
  networker_socket:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: 75b5ec0e51096ae169df3cd4f02c9f6affe22a81
      path: packages/networker/networker_socket
  flex_color_scheme: ^7.2.0
  flutter_svg: ^2.0.7
  window_manager: ^0.3.5
  # Database
  shared_preferences: ^2.2.0
  # Generation
  barcode: ^2.2.4
  # Internal
  flutter_bloc: ^8.1.3
  url_launcher: ^6.1.12
  freezed_annotation: ^2.4.1
  # Information
  http: ^1.1.0
  package_info_plus: ^5.0.1
  path_provider: ^2.0.15
  go_router: ^12.1.3
  json_annotation: ^4.8.1
  dynamic_color: ^1.6.7
  web_socket_channel: ^2.4.0
  rxdart: ^0.27.7
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  freezed: ^2.4.1
  json_serializable: ^6.7.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
