name: city_server
description: Libraries for Linwood City server and client
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shared:
    path: ../shared

dev_dependencies: 
  lints: ^1.0.1
