name: quokka_server
description: The Linwood Quokka game server
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.1

dependencies:
  args: ^2.4.2
  bloc: ^8.1.4
  logging: ^1.2.0
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      ref: 5a3658cad80fcb8594b8be6f84460e77607eb959
      path: packages/networker/networker
  networker_socket:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      ref: 00671cce35e995f203806b55bc6d6881fca0e107
      path: packages/networker/networker_socket
  path: ^1.9.0
  quokka_api:
    path: ../api

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
