name: quokka_server
description: The Linwood Quokka game server
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.1

dependencies:
  args: ^2.4.2
  bloc: ^8.1.4
  logging: ^1.2.0
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      ref: 699545d8be7fd267f0aac1481f39c0646bf2198e
      path: packages/networker/networker
  networker_socket:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      ref: 3d5b1e311fdc90bf2eaf3d948f08e1eb6098ab68
      path: packages/networker/networker_socket
  path: ^1.9.0
  quokka_api:
    path: ../api

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
