name: town_server
description: Server for the town app
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  shared:
    path: ../shared

dev_dependencies: 
  lints: ^2.0.1
