name: shared
description: Libraries for Linwood Town server and client
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.17.1
  equatable: ^2.0.5
  meta: ^1.8.0

dev_dependencies: 
  lints: ^2.0.1
