name: shared
description: Libraries for Linwood Town server and client
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  equatable: ^2.0.3
  meta: ^1.7.0
  networker:
    path: ../networker/networker
  networker_socket:
    path: ../networker/networker_socket
  networker_ble:
    path: ../networker/networker_ble

dev_dependencies: 
  lints: ^2.0.0
