name: setonix_tools
environment:
  sdk: ">=2.13.0 <3.0.0"
dependencies:
  archive: ^3.4.10
  args: ^2.5.0
  intl: ^0.19.0
  lints: ^5.0.0
  shelf: ^1.4.1
  shelf_proxy: ^1.0.4
  shelf_static: ^1.1.2
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.0
  yaml: ^3.1.2
  generate_leap:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      ref: 40b8553ab86ab4f06d9f689268a65d65ed936fda
      path: packages/generate_leap
