name: qeck_tools
environment:
  sdk: ">=2.13.0 <3.0.0"
dependencies:
  args: ^2.4.2
  intl: ^0.18.1
  lints: ^2.1.1
  shelf: ^1.4.1
  shelf_proxy: ^1.0.4
  shelf_static: ^1.1.2
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
  yaml: ^3.1.2
