name: setonix_api
description: The Linwood Setonix API
version: 0.2.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.5.1 <4.0.0"

# Add regular dependencies here.
dependencies:
  dart_mappable: ^4.2.2
  archive: ^4.0.2
  lw_file_system_api:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      ref: 5ab1b96bea6ef0e0c07629ff4e7152b4437cf8ee
      path: packages/lw_file_system_api
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      ref: 071e02761bf55a47bcde0cdc2a711b8ff5fbbb18
      path: packages/networker/networker
  dart_leap:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      path: packages/dart_leap
      ref: db69a03082e6811c58dc2d0e5c23d04305e1623f
  crypto: ^3.0.5
  collection: ^1.18.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  dart_mappable_builder: ^4.2.3
  build_runner: ^2.4.12
