name: Deploy documentation

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Deploy to SFTP
        if: github.ref == 'refs/heads/develop'
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_KEY: ${{ secrets.SFTP_KEY }}
        run: |
          echo "$SFTP_KEY" > sftp_key
          chmod 600 sftp_key
          scp -i sftp_key -r ./dist $SFTP_USERNAME@$SFTP_HOST:/var/www/www.setonix
